# Generated by Django 5.0.6 on 2024-07-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_payment_statues_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
    ]
