# Generated by Django 5.0.6 on 2024-06-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='test',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
